### ISSUE TITLE
fungus fungus error

### ISSUE THREAD

**Issue by jianshu93** [linnabrown/run_dbcan#56]
test all sueecssful but this error （I have the overview.txt file）：

Traceback (most recent call last):
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/run_dbcan/bin/list_multidomain_proteins.py", line 8, in <module>
    protein_collection = hotpep_data_path("fungus_fungus/Chaetomium_thermophilum")
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/run_dbcan/lib/python3.8/site-packages/run_dbcan-2.0.11-py3.8.egg/Hotpep/hotpep_data.py", line 8, in hotpep_data_path
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/run_dbcan/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1143, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/run_dbcan/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1754, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/run_dbcan/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1775, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'Hotpep/fungus_fungus/Chaetomium_thermophilum'

**Comment by linnabrown** [comment]
What's your command?
